### ISSUE TITLE
Unskinned elite borders

### ISSUE THREAD

**Issue by AmplusNLD** [gashole/modui-FocusFrame#1]
I tried to add unskinned elite borders like modui has. They do work if I add this code to the core,
but for some reason, the unskinned borders hide when you mouse-over the focused target after you de-targeted it.

Do you have a clue?

```lua
    FocusFrame.Elite = FocusFrameTextureFrame:CreateTexture(nil, 'BORDER')
    FocusFrame.Elite:SetTexture[[Interface\AddOns\modui\unitframe\UI-TargetingFrame-Elite]]
    FocusFrame.Elite:SetWidth(128)
    FocusFrame.Elite:SetHeight(128)
    FocusFrame.Elite:SetPoint('TOPRIGHT', FocusFrame)
    FocusFrame.Elite:Hide()

    FocusFrame.Rare = FocusFrameTextureFrame:CreateTexture(nil, 'BORDER')
    FocusFrame.Rare:SetTexture[[Interface\AddOns\modui\unitframe\UI-TargetingFrame-Rare-Elite]]
    FocusFrame.Rare:SetWidth(128)
    FocusFrame.Rare:SetHeight(128)
    FocusFrame.Rare:SetPoint('TOPRIGHT', FocusFrame)
    FocusFrame.Rare:Hide()	
		
    function FocusFrame_CheckClassification()
        local c = UnitClassification'target'
       FocusFrameTexture:SetTexture[[Interface\TargetingFrame\UI-TargetingFrame]]
       for _, v in pairs({FocusFrame.Elite, FocusFrame.Rare}) do
           v:Hide()
        end
        if  c == 'worldboss' or c == 'rareelite' or c == 'elite' then
            FocusFrame.Elite:Show()
        elseif c == 'rare' then
            FocusFrame.Rare:Show()
        end
    end
```

Also there need to be an extra line added for the FocusPvPIcon to be positioned correctly

```lua
FocusPVPIcon:ClearAllPoints()
```

**Comment by gashole** [comment]
function FocusFrame_CheckClassification()
       local c = UnitClassification'target'

should be

    function FocusFrame_CheckClassification(unit)
        local c = UnitClassification(unit)

> Also there need to be an extra line added for the FocusPvPIcon to be positioned correctly
>    `FocusPVPIcon:ClearAllPoints()`

Oops, I removed that and didn't notice.

Fixed by https://github.com/gashole/modui-FocusFrame/commit/9a5ef814982c1c8989032b04f6255f88b5114a2d and https://github.com/gashole/modui-FocusFrame/commit/80fe9d927d28748d827a36bce52a035b373bf4bf, thanks.
